title: We Are Open Cooperative
author: We Are Open Cooperative
email: admin@weareopen.coop
description: > # this means to ignore newlines until "baseurl:"
  A Site Starter Materialize Templates for Jekyll

twitter_username: weareopencoop
github_username:  laurahilliger

sass:
    style: compressed