--- 
author: "We Are Open Coop"
description: "A Site Starter Materialize Templates for Jekyll\n"
email: admin@weareopen.coop
github_username: laurahilliger
sass: 
  style: compressed
title: "We Are Open Coop"
twitter_username: weareopencoop
safe: true
lsi: false
source: materialize